name: weather_app_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^5.4.1
  dio: ^3.0.8
  flutter_svg: ^0.15.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/weather_baoyu.svg
   - images/weather_bingbao.svg
   - images/weather_daxue.svg
   - images/weather_dayu.svg
   - images/weather_duoyun.svg
   - images/weather_leiyu.svg
   - images/weather_qing.svg
   - images/weather_shachen.svg
   - images/weather_shuang.svg
   - images/weather_wumai.svg
   - images/weather_xiaoxue.svg
   - images/weather_xiaoyu.svg
   - images/weather_xiaoyuzhuanqing.svg
   - images/weather_xuezhuanqing.svg
   - images/weather_ye.svg
   - images/weather_yeduoyun.svg
   - images/weather_yintian.svg
   - images/weather_yujiaxue.svg
   - images/weather_zhongxue.svg
   - images/weather_zhongyu.svg
   - images/list_fengli.png
   - images/list_ludian.png
   - images/list_nengjiandu.png
   - images/list_qiwen.png
   - images/list_qiya.png
   - images/list_shidu.png
   - images/list_yuexiang.png
   - images/list_ziwaixian.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
